### ISSUE TITLE
Previewing Stream in MediaPackage console. get error 'Sorry, something went wrong'

### ISSUE THREAD

**Issue by 29er** [aws-samples/aws-media-services-simple-live-workflow#17]
Following along with this lab and got to the 4-BroswerPage module.
1) Navigate to the AWS Elemental MediaPackage console.
2 ) Select the channel you created previously.
3 )Find the origin endpoint on the channel page.
4 ) Click the Play link under the Preview column to test with the embedded player
Afer clicking Play on the first/second endpoint.
tried in both safari and chrome. same error on both.

![Screen Shot 2019-09-05 at 10 00 08 AM](https://user-images.githubusercontent.com/796719/64358610-02431080-cfc4-11e9-9704-608340c7d73c.png)
![Screen Shot 2019-09-05 at 10 01 03 AM](https://user-images.githubusercontent.com/796719/64358656-1850d100-cfc4-11e9-8bae-9e28cf874230.png)

**Comment by 29er** [comment]
user error

**Comment by dinhxuanduy** [comment]
hi, can you share about this it, i'm facing it but can't get the solution

**Comment by 29er** [comment]
I don't quite remember, but I had not followed the instructions exactly. go back and double check the steps

**Comment by stevenlafl** [comment]
Same problem. Followed https://d2908q01vomqb2.cloudfront.net/fb644351560d8296fe6da332236b1f8d61b2828a/2020/04/14/Connecting-OBS-Studio-to-AWS-Media-Services-in-the-Cloud-v2.pdf exactly. 

Then, followed https://www.youtube.com/watch?time_continue=968&v=Rwvta8_INHY&feature=emb_logo exactly.

Both result in the same problem. The video can't be played on mobile (different network entirely on cell towers), can't be played using a different player, and the m3u8 URL results in a 404.

**Comment by morjoan** [comment]
@stevenlafl Without seeing your setup, my guess is that MediaLive is failing to send video to MediaPackage that's why no manifest is getting generated (m3u8 is getting a 404). I would double check your MediaLive settings per instructions you're following and once your channel has started, make sure there are no alerts whatsoever. One of the most common things to get wrong is copy/pasting incorrect username and password for the MediaPackage inputs (extra space, putting password for the username, etc). Hope this helps.
